
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 18;
  public static final int union = 10;
  public static final int coma = 2;
  public static final int llave_abre = 6;
  public static final int porcentajes = 20;
  public static final int flecha = 5;
  public static final int llave_cierra = 7;
  public static final int lesinespacio = 19;
  public static final int positivo = 12;
  public static final int conj = 15;
  public static final int caracter = 14;
  public static final int punto = 9;
  public static final int ptcoma = 4;
  public static final int digito = 16;
  public static final int EOF = 0;
  public static final int id = 17;
  public static final int error = 1;
  public static final int interrogacion = 13;
  public static final int virgulilla_char = 8;
  public static final int dospuntos = 3;
  public static final int kleene = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "dospuntos",
  "ptcoma",
  "flecha",
  "llave_abre",
  "llave_cierra",
  "virgulilla_char",
  "punto",
  "union",
  "kleene",
  "positivo",
  "interrogacion",
  "caracter",
  "conj",
  "digito",
  "id",
  "cadena",
  "lesinespacio",
  "porcentajes"
  };
}

